// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface UpdateCristinRepo {
  /**
   * Name of repository
   */
  repo: "no.item.cristin.institutions" | "no.item.cristin.persons" | "no.item.cristin.projects" | "no.item.cristin.results" | "no.item.cristin.units" | "no.item.cristin.resultcontributors" | "no.item.cristin.fundings";
}
